import { Language } from './types';

export const LANGUAGES: { code: Language; name: string; label: string }[] = [
  { code: 'en', name: 'English', label: 'ENG' },
  { code: 'zh', name: '中文', label: '中文' },
  { code: 'th', name: 'ไทย', label: 'THAI' },
  { code: 'vi', name: 'Tiếng Việt', label: 'VIET' },
  { code: 'id', name: 'Bahasa Indonesia', label: 'IND' },
];

export const ADMIN_FEE = 15;

export const COLORS = {
  primary: '#10B981', // Emerald 500
  secondary: '#3B82F6', // Blue 500
  accent: '#F59E0B', // Amber 500
  background: '#09090B', // Zinc 950
  surface: '#18181B', // Zinc 900
  text: '#F4F4F5', // Zinc 100
};

export const TRANSLATIONS = {
  id: {
    home: 'Beranda',
    ride: 'Halloride',
    food: 'Hallofood',
    send: 'Hallosend',
    pay: 'Hallopay',
    profile: 'Profil',
    welcome: 'All-in-one service platform',
    whereTo: 'Mau ke mana hari ini?',
    orderNow: 'Pesan Sekarang',
    halal: 'Halal',
    indonesian: 'Indonesia',
    taiwanese: 'Taiwan',
    nearby: 'Terdekat',
    balance: 'Saldo',
    history: 'Riwayat',
    topup: 'Isi Saldo',
    seller: 'Penjual',
    rider: 'Rider',
    customer: 'Pelanggan',
    selectRole: 'Pilih Peran Anda',
    signUp: 'Daftar',
    signIn: 'Daftar',
    logIn: 'Masuk',
    email: 'Email',
    password: 'Kata Sandi',
    fullName: 'Nama Lengkap',
    dob: 'Tanggal Lahir',
    day: 'Hari',
    month: 'Bulan',
    year: 'Tahun',
    process: 'Memproses',
    verifyEmail: 'Verifikasi Email',
    verificationSent: 'Tautan verifikasi telah dikirim ke email Anda.',
    backToLogin: 'Kembali ke Masuk',
    forgotPassword: 'Lupa Kata Sandi?',
    resetPassword: 'Atur Ulang Kata Sandi',
    resetLinkSent: 'Tautan atur ulang kata sandi telah dikirim ke email Anda.',
    sendResetLink: 'Kirim Tautan Atur Ulang',
    enterRegisteredEmail: 'Masukkan email terdaftar Anda',
    adminFee: 'Biaya Admin',
    phonePlaceholder: 'Nomor Telepon (misal: 0912...)',
  },
  zh: {
    home: '首頁',
    ride: 'Halloride',
    food: 'Hallofood',
    send: 'Hallosend',
    pay: 'Hallopay',
    profile: '個人資料',
    welcome: 'All-in-one service platform',
    whereTo: '今天想去哪裡？',
    orderNow: '立即訂購',
    halal: '清真',
    indonesian: '印尼料理',
    taiwanese: '台灣料理',
    nearby: '附近',
    balance: '餘額',
    history: '歷史記錄',
    topup: '儲值',
    seller: '賣家',
    rider: '外送員',
    customer: '客戶',
    selectRole: '選擇您的角色',
    signUp: '註冊',
    signIn: '註冊',
    logIn: '登錄',
    email: '電子郵件',
    password: '密碼',
    fullName: '全名',
    dob: '出生日期',
    day: '日',
    month: '月',
    year: '年',
    process: '處理中',
    verifyEmail: '驗證電子郵件',
    verificationSent: '驗證連結已發送到您的電子郵件。',
    backToLogin: '返回登錄',
    forgotPassword: '忘記密碼？',
    adminFee: '行政費',
    phonePlaceholder: '電話號碼 (例如: 0912...)',
  },
  en: {
    home: 'Home',
    ride: 'Halloride',
    food: 'Hallofood',
    send: 'Hallosend',
    pay: 'Hallopay',
    profile: 'Profile',
    welcome: 'All-in-one service platform',
    whereTo: 'Where to today?',
    orderNow: 'Order Now',
    halal: 'Halal',
    indonesian: 'Indonesian',
    taiwanese: 'Taiwanese',
    nearby: 'Nearby',
    balance: 'Balance',
    history: 'History',
    topup: 'Top Up',
    seller: 'Seller',
    rider: 'Rider',
    customer: 'Customer',
    selectRole: 'Select Your Role',
    signUp: 'Sign Up',
    signIn: 'Sign Up',
    logIn: 'Log In',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    dob: 'Date of Birth',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    process: 'Process',
    verifyEmail: 'Verify Email',
    verificationSent: 'A verification link has been sent to your email.',
    backToLogin: 'Back to Login',
    forgotPassword: 'Forgot Password?',
    adminFee: 'Admin Fee',
    phonePlaceholder: 'Phone Number (e.g., 0912...)',
  },
  th: {
    home: 'หน้าแรก',
    ride: 'Halloride',
    food: 'Hallofood',
    send: 'Hallosend',
    pay: 'Hallopay',
    profile: 'โปรไฟล์',
    welcome: 'All-in-one service platform',
    whereTo: 'วันนี้ไปไหนดี?',
    orderNow: 'สั่งเลย',
    halal: 'ฮาลาล',
    indonesian: 'อินโดนีเซีย',
    taiwanese: 'ไต้หวัน',
    nearby: 'ใกล้เคียง',
    balance: 'ยอดเงิน',
    history: 'ประวัติ',
    topup: 'เติมเงิน',
    seller: 'ผู้ขาย',
    rider: 'ไรเดอร์',
    customer: 'ลูกค้า',
    selectRole: 'เลือกบทบาทของคุณ',
    signUp: 'ลงทะเบียน',
    signIn: 'ลงทะเบียน',
    logIn: 'เข้าสู่ระบบ',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    fullName: 'ชื่อเต็ม',
    dob: 'วันเกิด',
    day: 'วัน',
    month: 'เดือน',
    year: 'ปี',
    process: 'กำลังดำเนินการ',
    verifyEmail: 'ยืนยันอีเมล',
    verificationSent: 'ส่งลิงก์ยืนยันไปที่อีเมลของคุณแล้ว',
    backToLogin: 'กลับไปที่หน้าเข้าสู่ระบบ',
    forgotPassword: 'ลืมรหัสผ่าน?',
    adminFee: 'ค่าธรรมเนียมแอดมิน',
    phonePlaceholder: 'หมายเลขโทรศัพท์ (เช่น 0912...)',
  },
  vi: {
    home: 'Trang chủ',
    ride: 'Halloride',
    food: 'Hallofood',
    send: 'Hallosend',
    pay: 'Hallopay',
    profile: 'Hồ sơ',
    welcome: 'All-in-one service platform',
    whereTo: 'Hôm nay đi đâu?',
    orderNow: 'Đặt ngay',
    halal: 'Halal',
    indonesian: 'Indonesia',
    taiwanese: 'Đài Loan',
    nearby: 'Gần đây',
    balance: 'Số dư',
    history: 'Lịch sử',
    topup: 'Nạp tiền',
    seller: 'Người bán',
    rider: 'Tài xế',
    customer: 'Khách hàng',
    selectRole: 'Chọn vai trò của bạn',
    signUp: 'Đăng ký',
    signIn: 'Đăng ký',
    logIn: 'Đăng nhập',
    email: 'Email',
    password: 'Mật khẩu',
    fullName: 'Họ và tên',
    dob: 'Ngày sinh',
    day: 'Ngày',
    month: 'Tháng',
    year: 'Năm',
    process: 'Đang xử lý',
    verifyEmail: 'Xác minh Email',
    verificationSent: 'Một liên kết xác minh đã được gửi đến email của bạn.',
    backToLogin: 'Quay lại Đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    adminFee: 'Phí quản lý',
    phonePlaceholder: 'Số điện thoại (ví dụ: 0912...)',
  },
};
